package main

import (
	"io/ioutil"
	"log"
	"os"
	"path"
	"strings"
)

const dirname = "maps"

// Reads all .txt files in the current folder
// and encodes them as strings literals in textfiles.go
func main() {
	fs, _ := ioutil.ReadDir(dirname)
	out, _ := os.Create("validators/maps.go")
	out.Write([]byte("// Code generated by includemaps.go; DO NOT EDIT.\n\npackage validators\n\nvar (\n"))
	out.Write([]byte("  // Data embedded version of the maps/*.json used at generation time\n  Data = map[string]string{\n"))
	for _, f := range fs {
		if strings.HasSuffix(f.Name(), ".json") {

			out.Write([]byte("    \"" + f.Name() + "\": `"))
			log.Printf("adding %s ", f.Name())
			f, _ := ioutil.ReadFile(path.Join(dirname, f.Name()))
			str := strings.Replace(string(f), "`", "'", -1)
			out.Write([]byte(str))
			out.Write([]byte("`,\n"))
		}
	}
	out.Write([]byte("  }\n)\n"))
}
