// Code generated by generate/generate.go; DO NOT EDIT.

package handlers

import (
	"encoding/json"

	"github.com/sul-dlss-labs/taco/datautils"
)
var (
  // fileTemplate the defaults extracted from maps/DepositFile.json
  fileTemplate = `{"@context":"http://sdr.sul.stanford.edu/contexts/taco-base.jsonld","@type":"http://sdr.sul.stanford.edu/models/sdr3-file.jsonld","access":{"access":"dark","download":"dark"},"administrative":{"deleted":false,"sdrPreserve":false},"identification":{},"structural":{},"version":0}`
)

// NewFile creates a new instance of a File resource using the defaults in fileTemplate
func NewFile() *datautils.Resource {
  var resourceData datautils.JSONObject
  json.Unmarshal([]byte(fileTemplate), &resourceData)
  return datautils.NewResource(resourceData)
}
