// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi TACO
TACO, the Stanford Digital Repository (SDR) Management Layer interface


    Schemes:
      http
    Host: sdr.dlss.stanford.edu
    BasePath: /v1
    Version: 0.0.1
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
