// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Stanford Digital Repository
The SDR management interface


    Schemes:
      http
    Host: sdr.dlss.stanford.edu
    BasePath: /v1
    Version: 3.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json
    - application/xml

    Produces:
    - application/json
    - application/xml

swagger:meta
*/
package restapi
