// Code generated by generate/generate.go; DO NOT EDIT.

package validators

var (
  // Data embedded version of the maps/*.json used at generation time
  Data = map[string]string{
    "Agent.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Agent",
  "description": "An Agent - Person, Group, Organization, or other Acting body.",
  "type": "object",
  "required": ["name"],
  "properties": {
    "name": {
      "description": "Primary label or name for an Agent.",
      "type": "string"
    },
    "sunetID": {
      "description": "Stanford University NetID for the Agent.",
      "type": "string"
    }
  }
}
`,
    "Collection.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Digital Repository Collection",
  "description": "A group of Digital Repository Objects that indicate some type of conceptual grouping within the domain that is worth reusing across the system.",
  "type": "object",
  "required": ["@context", "@type", "externalIdentifier", "label", "tacoIdentifier", "version", "administrative", "access", "identification", "structural"],
  "properties": {
    "@context": {
      "description": "URI for the JSON-LD context definitions.",
      "type": "string"
    },
    "@type": {
      "description": "The content type of the Collection. Selected from an established set of values.",
      "type": "string",
      "enum": [
        "http://sdr.sul.stanford.edu/models/sdr3-collection.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-curated-collection.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-user-collection.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-exhibit.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-series.jsonld"
      ]
    },
    "citation": {
      "description": "Citation for the resource, including identifier, label, version, and a persistent URL to the object with SDR at the very least.",
      "type": "string"
    },
    "dedupeIdentifier": {
      "description": "Identifier retrieved from identification.sourceId that stands for analog or source identifier that this resource is a digital representation of.",
      "type": "string"
    },
    "depositor": {
      "description": "The Agent (User, Group, Application, Department, other) that deposited the Collection into SDR.",
      "$ref": "Agent.json"
    },
    "externalIdentifier": {
      "description": "Identifier for the resource within SDR but outside of TACO. DRUID or UUID depending on resource type. Constant across resource versions. What clients will use calling TACO. Same as 'identification.identifier'",
      "type": "string"
    },
    "label": {
      "description": "Primary processing label (can be same as title) for a Collection.",
      "type": "string"
    },
    "tacoIdentifier": {
      "description": "Identifier for the resource within TACO. UUID, unique for each new version of a TACO resource.",
      "type": "string"
    },
    "version": {
      "description": "Version for the Collection within SDR.",
      "type": "integer"
    },
    "precedingVersion": {
      "description": "Preceding version for the Collection within SDR.",
      "type": "string"
    },
    "followingVersion": {
      "description": "Following version for the Collection within SDR.",
      "type": "string"
    },
    "access": {
      "description": "Access Metadata for the Collection.",
      "type": "object",
      "required": ["access", "download"],
      "properties": {
        "access": {
          "description": "Access level for the Collection.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "copyright": {
          "description": "The human readable copyright statement that applies to the Collection.",
          "type": "string"
        },
        "download": {
          "description": "Download level for the Collection metadata.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "embargoReleaseDate": {
          "description": "Date when the Collection is released from an embargo, if an embargo exists.",
          "type": "string",
          "format": "date-time"
        },
        "license": {
          "description": "The license governing reuse of the Collection. Should be an IRI for known licenses (i.e. CC, RightsStatement.org URI, etc.).",
          "type": "string"
        },
        "reuseAndReproductionStatement": {
          "description": "The human readable reuse and reproduction statement that applies to the Collection.",
          "type": "string"
        },
        "termsOfUse": {
          "description": "License or terms of use governing reuse of the Collection. Should be a text statement.",
          "type": "string"
        }
      }
    },
    "administrative": {
      "type": "object",
      "description": "Administrative metadata for the SDR resource.",
      "required": ["created", "isDescribedBy", "sdrPreserve"],
      "properties": {
        "created": {
          "description": "When the resource in SDR was created.",
          "type": "string",
          "format": "date-time"
        },
        "deleted": {
          "description": "If the resource has been deleted (but not purged).",
          "type": "boolean"
        },
        "gravestoneMessage": {
          "description": "Message describing why the object was deleted.",
          "type": "string"
        },
        "isDescribedBy": {
          "description": "PURL/XML file that is a traditional representation of the metadata for the Collection.",
          "type": "string"
        },
        "lastUpdated": {
          "description": "When the resource in SDR was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "partOfProject": {
          "description": "Administrative or Internal project this resource is a part of.",
          "type": "string"
        },
        "sdrPreserve": {
          "description": "If this resource should be sent to Preservation.",
          "type": "boolean"
        },
        "remediatedBy": {
          "description": "The Agent (User, Group, Application, Department, other) that remediated a Collection in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "identification": {
      "description": "Identifying information for the Collection.",
      "type": "object",
      "required": ["identifier"],
      "properties": {
        "catalogLinks": {
          "description": "Links to catalog records for the resource that the Collection represents in whole or part.",
          "type": "array",
          "items": {
            "type": "object",
            "required": ["catalog", "catalogRecordId"],
            "properties": {
              "catalog": {
                "description": "Catalog that is the source of the linked record.",
                "type": "string"
              },
              "catalogRecordId": {
                "description": "Record identifier that is unique within the context of the linked record's catalog.",
                "type": "string"
              },
              "recordSchema": {
                "description": "Metadata schema of the linked record.",
                "type": "string"
              },
              "deriveMetadata": {
                "description": "If the Collection descriptive metadata should be automatically updated when the linked record changes.",
                "type": "boolean"
              },
              "deliverMetadata": {
                "description": "If the linked record should be automatically updated when the Collection descriptive metadata changes.",
                "type": "boolean"
              },
              "recordScope": {
                "description": "Whether the linked record describes a resource that is broader than, equivalent to, or narrower than the resource the Collection represents.",
                "type": "string",
                "enum": ["broader", "equivalent", "narrower"]
              }
            }
          }
        },
        "DOI": {
          "description": "Digital Object Identifier (DOI) for the Collection within this repository.",
          "type": "string"
        },
        "identifier": {
          "description": "Identifier for the Collection within the Stanford Digital Repository system",
          "type": "string"
        },
        "sameAs": {
          "description": "Another object, either external or internal to the system (if duplication occurs) that is the same digital resource as this Collection.",
          "type": "string"
        },
        "sourceId": {
          "description": "A source resource or object (perhaps but not necessarily analog or physical) that the Collection is a digital representation of.",
          "type": "string"
        },
        "sdrUUID": {
          "type": "string",
          "description": "UUID previously minted for the resource within SDR2 / Fedora 3."
        }
      }
    },
    "structural": {
      "description": "Structural metadata for the Collection.",
      "type": "object",
      "required": ["hasAgreement"],
      "properties": {
        "hasAgreement": {
          "description": "Agreement that covers the deposit of the Collection into SDR.",
          "type": "string"
        },
        "hasMember": {
          "description": "Component digital repository objects or collections that are a part of this collection.",
          "type": "array",
          "items": [{
            "type": "string"
          }]
        },
        "isTargetOf": {
          "description": "An Annotation instance that applies to the Collection.",
          "type": ["string", "null"]
        },
        "hasMemberOrders": {
          "description": "Provided sequences or orderings of members of the Collection, including some metadata about each sequence (i.e. sequence label, sequence type, if the sequence is primary, etc.).",
          "type": "array",
          "items": [
            {
              "$ref": "Sequence.json"
            }
          ]
        }
      }
    }
  }
}
`,
    "DRO.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Digital Repository Object",
  "description": "Domain-defined abstraction of a 'work'. Digital Repository Objects' abstraction is describable for our domain’s purposes, i.e. for management needs within our system.",
  "type": "object",
  "required": ["@context", "@type", "externalIdentifier", "label", "tacoIdentifier", "version", "administrative", "access", "identification", "structural"],
  "properties": {
    "@context": {
      "description": "URI for the JSON-LD context definitions.",
      "type": "string"
    },
    "@type": {
      "description": "The content type of the DRO. Selected from an established set of values.",
      "type": "string",
      "enum": [
        "http://sdr.sul.stanford.edu/models/sdr3-object.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-3d.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-agreement.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-book.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-document.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-geo.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-image.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-page.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-photograph.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-manuscript.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-map.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-media.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-track.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-webarchive-binary.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-webarchive-seed.jsonld"
      ]
    },
    "citation": {
      "description": "Citation for the resource, including identifier, label, version, and a persistent URL to the object with SDR at the very least.",
      "type": "string"
    },
    "dedupeIdentifier": {
      "description": "Identifier retrieved from identification.sourceId that stands for analog or source identifier that this resource is a digital representation of.",
      "type": "string"
    },
    "depositor": {
      "description": "The Agent (User, Group, Application, Department, other) that deposited the DRO into SDR.",
      "$ref": "Agent.json"
    },
    "externalIdentifier": {
      "description": "Identifier for the resource within SDR but outside of TACO. DRUID or UUID depending on resource type. Constant across resource versions. What clients will use calling TACO. Same as 'identification.identifier'",
      "type": "string"
    },
    "label": {
      "description": "Primary processing label (can be same as title) for a DRO.",
      "type": "string"
    },
    "tacoIdentifier": {
      "description": "Identifier for the resource within TACO. UUID, unique for each new version of a TACO resource.",
      "type": "string"
    },
    "version": {
      "description": "Version for the DRO within SDR.",
      "type": "integer"
    },
    "precedingVersion": {
      "description": "Preceding version for the Object within SDR.",
      "type": "string"
    },
    "followingVersion": {
      "description": "Following version for the Object within SDR.",
      "type": "string"
    },
    "access": {
      "description": "Access Metadata for the DRO.",
      "type": "object",
      "required": ["access", "download"],
      "properties": {
        "access": {
          "description": "Access level for the DRO.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "copyright": {
          "description": "The human readable copyright statement that applies to the DRO.",
          "type": "string"
        },
        "download": {
          "description": "Download level for the DRO metadata.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "embargoReleaseDate": {
          "description": "Date when the DRO is released from an embargo, if an embargo exists.",
          "type": "string",
          "format": "date-time"
        },
        "license": {
          "description": "The license governing reuse of the DRO. Should be an IRI for known licenses (i.e. CC, RightsStatement.org URI, etc.).",
          "type": "string"
        },
        "reuseAndReproductionStatement": {
          "description": "The human readable reuse and reproduction statement that applies to the DRO.",
          "type": "string"
        },
        "termsOfUse": {
          "description": "License or terms of use governing reuse of the DRO. Should be a text statement.",
          "type": "string"
        },
        "visibility": {
          "description": "Percentage of the DRO that is visibility during an embargo period",
          "type": "integer"
        }
      }
    },
    "administrative": {
      "type": "object",
      "description": "Administrative metadata for the SDR resource.",
      "required": ["created", "isDescribedBy", "sdrPreserve"],
      "properties": {
        "created": {
          "description": "When the resource in SDR was created.",
          "type": "string",
          "format": "date-time"
        },
        "deleted": {
          "description": "If the resource has been deleted (but not purged).",
          "type": "boolean"
        },
        "gravestoneMessage": {
          "description": "Message describing why the object was deleted.",
          "type": "string"
        },
        "isDescribedBy": {
          "description": "Pointer to the PURL/XML file that is a traditional representation of the metadata for the DRO.",
          "type": "string"
        },
        "lastUpdated": {
          "description": "When the resource in SDR was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "partOfProject": {
          "description": "Administrative or Internal project this resource is a part of.",
          "type": "string"
        },
        "sdrPreserve": {
          "description": "If this resource should be sent to Preservation.",
          "type": "boolean"
        },
        "remediatedBy": {
          "description": "The Agent (User, Group, Application, Department, other) that remediated a DRO in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "identification": {
      "description": "Identifying information for the DRO.",
      "type": "object",
      "required": ["identifier"],
      "properties": {
        "catalogLinks": {
          "description": "Links to catalog records for the resource that the DRO represents in whole or part.",
          "type": "array",
          "items": {
            "type": "object",
            "required": ["catalog", "catalogRecordId"],
            "properties": {
              "catalog": {
                "description": "Catalog that is the source of the linked record.",
                "type": "string"
              },
              "catalogRecordId": {
                "description": "Record identifier that is unique within the context of the linked record's catalog.",
                "type": "string"
              },
              "recordSchema": {
                "description": "Metadata schema of the linked record.",
                "type": "string"
              },
              "deriveMetadata": {
                "description": "If the DRO descriptive metadata should be automatically updated when the linked record changes.",
                "type": "boolean"
              },
              "deliverMetadata": {
                "description": "If the linked record should be automatically updated when the DRO descriptive metadata changes.",
                "type": "boolean"
              },
              "recordScope": {
                "description": "Whether the linked record describes a resource that is broader than, equivalent to, or narrower than the resource the DRO represents.",
                "type": "string",
                "enum": ["broader", "equivalent", "narrower"]
              }
            }
          }
        },
        "doi": {
          "description": "Digital Object Identifier (DOI) for the DRO within this repository.",
          "type": "string"
        },
        "identifier": {
          "description": "Identifier for the Digital Repository Object within the Stanford Digital Repository system",
          "type": "string"
        },
        "sameAs": {
          "description": "Another object, either external or internal to the system (if duplication occurs) that is the same digital resource as this DRO.",
          "type": "string"
        },
        "sourceId": {
          "description": "A source resource or object (perhaps but not necessarily analog or physical) that the DRO is a digital representation of.",
          "type": "string"
        },
        "sdrUUID": {
          "type": "string",
          "description": "UUID previously minted for the resource within SDR2 / Fedora 3."
        }
      }
    },
    "permissions": {
      "description": "Permissions Metadata for the DRO.",
      "type": "object",
      "properties": {
        "approvalRequired": {
          "description": "Indicates if approval is required to deposit or manage the resource in SDR.",
          "type": "boolean"
        },
        "approvers": {
          "description": "Agents who are required to approve deposit or management of this resource in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "structural": {
      "description": "Structural metadata for the DRO.",
      "type": "object",
      "required": ["hasAgreement"],
      "properties": {
        "contains": {
          "$comment": "This property is deprecated. Assert isContainedBy on the Fileset instead.",
          "description": "Filesets that contain the digital representations (Files) of the DRO.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "hasAgreement": {
          "description": "Agreement that covers the deposit of the DRO into SDR.",
          "type": "string"
        },
        "hasMember": {
          "description": "Component or 'children' digital repository objects that are a part or portion of this 'parent' or aggregate DRO.",
          "type": "array",
          "items": [{
            "type": "string"
          }]
        },
        "isTargetOf": {
          "description": "An Annotation instance that applies to the DRO.",
          "type": ["string", "null"]
        },
        "hasMemberOrders": {
          "description": "Provided sequences or orderings of members of the Object, including some metadata about each sequence (i.e. sequence label, sequence type, if the sequence is primary, etc.).",
          "type": "array",
          "items": [{
            "$ref": "Sequence.json"
          }]
        }
      }
    }
  }
}
`,
    "DepositCollection.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Digital Repository Collection",
  "description": "A group of Digital Repository Objects that indicate some type of conceptual grouping within the domain that is worth reusing across the system.",
  "type": "object",
  "required": ["@context", "@type", "label", "administrative", "access", "identification", "structural"],
  "not": {
    "anyOf": [
      { "required": ["tacoIdentifier"] },
      { "required": ["version"] },
      { "required": ["externalIdentifier"] }
    ]
  },
  "properties": {
    "@context": {
      "description": "URI for the JSON-LD context definitions.",
      "type": "string"
    },
    "@type": {
      "description": "The content type of the Collection. Selected from an established set of values.",
      "type": "string",
      "enum": [
        "http://sdr.sul.stanford.edu/models/sdr3-collection.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-curated-collection.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-user-collection.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-exhibit.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-series.jsonld"
      ]
    },
    "citation": {
      "description": "Citation for the resource, including identifier, label, version, and a persistent URL to the object with SDR at the very least.",
      "type": "string"
    },
    "dedupeIdentifier": {
      "description": "Identifier retrieved from identification.sourceId that stands for analog or source identifier that this resource is a digital representation of.",
      "type": "string"
    },
    "depositor": {
      "description": "The Agent (User, Group, Application, Department, other) that deposited the Collection into SDR.",
      "$ref": "Agent.json"
    },
    "externalIdentifier": {
      "description": "Identifier for the resource within SDR but outside of TACO. DRUID or UUID depending on resource type. Constant across resource versions. What clients will use calling TACO. Same as 'identification.identifier'",
      "type": "string"
    },
    "label": {
      "description": "Primary processing label (can be same as title) for a Collection.",
      "type": "string"
    },
    "tacoIdentifier": {
      "description": "Identifier for the resource within TACO. UUID, unique for each new version of a TACO resource.",
      "type": "string"
    },
    "version": {
      "description": "Version for the Collection within SDR.",
      "type": "integer"
    },
    "precedingVersion": {
      "description": "Preceding version for the Collection within SDR.",
      "type": "string"
    },
    "followingVersion": {
      "description": "Following version for the Collection within SDR.",
      "type": "string"
    },
    "access": {
      "description": "Access Metadata for the Collection.",
      "type": "object",
      "required": ["access", "download"],
      "properties": {
        "access": {
          "description": "Access level for the Collection.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "copyright": {
          "description": "The human readable copyright statement that applies to the Collection.",
          "type": "string"
        },
        "download": {
          "description": "Download level for the Collection metadata.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "embargoReleaseDate": {
          "description": "Date when the Collection is released from an embargo, if an embargo exists.",
          "type": "string",
          "format": "date-time"
        },
        "license": {
          "description": "The license governing reuse of the Collection. Should be an IRI for known licenses (i.e. CC, RightsStatement.org URI, etc.).",
          "type": "string"
        },
        "reuseAndReproductionStatement": {
          "description": "The human readable reuse and reproduction statement that applies to the Collection.",
          "type": "string"
        },
        "termsOfUse": {
          "description": "License or terms of use governing reuse of the Collection. Should be a text statement.",
          "type": "string"
        }
      }
    },
    "administrative": {
      "type": "object",
      "description": "Administrative metadata for the SDR resource.",
      "required": ["sdrPreserve"],
      "not": {
        "anyOf": [
          { "required": ["created"] },
          { "required": ["isDescribedBy"] },
          { "required": ["lastUpdated"] }
        ]
      },
      "properties": {
        "created": {
          "description": "When the resource in SDR was created.",
          "type": "string",
          "format": "date-time"
        },
        "deleted": {
          "description": "If the resource has been deleted (but not purged).",
          "type": "boolean"
        },
        "gravestoneMessage": {
          "description": "Message describing why the object was deleted.",
          "type": "string"
        },
        "isDescribedBy": {
          "description": "PURL/XML file that is a traditional representation of the metadata for the Collection.",
          "type": "string"
        },
        "lastUpdated": {
          "description": "When the resource in SDR was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "partOfProject": {
          "description": "Administrative or Internal project this resource is a part of.",
          "type": "string"
        },
        "sdrPreserve": {
          "description": "If this resource should be sent to Preservation.",
          "type": "boolean"
        },
        "remediatedBy": {
          "description": "The Agent (User, Group, Application, Department, other) that remediated a Collection in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "identification": {
      "description": "Identifying information for the Collection.",
      "type": "object",
      "not": {"required": ["identifier"]},
      "properties": {
        "catalogLinks": {
          "description": "Links to catalog records for the resource that the Collection represents in whole or part.",
          "type": "array",
          "items": {
            "type": "object",
            "required": ["catalog", "catalogRecordId"],
            "properties": {
              "catalog": {
                "description": "Catalog that is the source of the linked record.",
                "type": "string"
              },
              "catalogRecordId": {
                "description": "Record identifier that is unique within the context of the linked record's catalog.",
                "type": "string"
              },
              "recordSchema": {
                "description": "Metadata schema of the linked record.",
                "type": "string"
              },
              "deriveMetadata": {
                "description": "If the Collection descriptive metadata should be automatically updated when the linked record changes.",
                "type": "boolean"
              },
              "deliverMetadata": {
                "description": "If the linked record should be automatically updated when the Collection descriptive metadata changes.",
                "type": "boolean"
              },
              "recordScope": {
                "description": "Whether the linked record describes a resource that is broader than, equivalent to, or narrower than the resource the Collection represents.",
                "type": "string",
                "enum": ["broader", "equivalent", "narrower"]
              }
            }
          }
        },
        "DOI": {
          "description": "Digital Object Identifier (DOI) for the Collection within this repository.",
          "type": "string"
        },
        "identifier": {
          "description": "Identifier for the Collection within the Stanford Digital Repository system",
          "type": "string"
        },
        "sameAs": {
          "description": "Another object, either external or internal to the system (if duplication occurs) that is the same digital resource as this Collection.",
          "type": "string"
        },
        "sourceId": {
          "description": "A source resource or object (perhaps but not necessarily analog or physical) that the Collection is a digital representation of.",
          "type": "string"
        },
        "sdrUUID": {
          "type": "string",
          "description": "UUID previously minted for the resource within SDR2 / Fedora 3."
        }
      }
    },
    "structural": {
      "description": "Structural metadata for the Collection.",
      "type": "object",
      "required": ["hasAgreement"],
      "properties": {
        "hasAgreement": {
          "description": "Agreement that covers the deposit of the Collection into SDR.",
          "type": "string"
        },
        "hasMember": {
          "description": "Component digital repository objects or collections that are a part of this collection.",
          "type": "array",
          "items": [{
            "type": "string"
          }]
        },
        "isTargetOf": {
          "description": "An Annotation instance that applies to the Collection.",
          "type": ["string", "null"]
        },
        "hasMemberOrders": {
          "description": "Provided sequences or orderings of members of the Collection, including some metadata about each sequence (i.e. sequence label, sequence type, if the sequence is primary, etc.).",
          "type": "array",
          "items": [
            {
              "$ref": "Sequence.json"
            }
          ]
        }
      }
    }
  }
}
`,
    "DepositDRO.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Digital Repository Object",
  "description": "Domain-defined abstraction of a 'work'. Digital Repository Objects' abstraction is describable for our domain’s purposes, i.e. for management needs within our system.",
  "type": "object",
  "required": ["@context", "@type", "label", "administrative", "access", "identification", "structural"],
  "not": {
    "anyOf": [
      { "required": ["tacoIdentifier"] },
      { "required": ["version"] },
      { "required": ["externalIdentifier"] }
    ]
  },
  "properties": {
    "@context": {
      "description": "URI for the JSON-LD context definitions.",
      "type": "string"
    },
    "@type": {
      "description": "The content type of the DRO. Selected from an established set of values.",
      "type": "string",
      "enum": [
        "http://sdr.sul.stanford.edu/models/sdr3-object.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-3d.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-agreement.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-book.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-document.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-geo.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-image.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-page.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-photograph.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-manuscript.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-map.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-media.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-track.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-webarchive-binary.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-webarchive-seed.jsonld"
      ]
    },
    "citation": {
      "description": "Citation for the resource, including identifier, label, version, and a persistent URL to the object with SDR at the very least.",
      "type": "string"
    },
    "dedupeIdentifier": {
      "description": "Identifier retrieved from identification.sourceId that stands for analog or source identifier that this resource is a digital representation of.",
      "type": "string"
    },
    "depositor": {
      "description": "The Agent (User, Group, Application, Department, other) that deposited the DRO into SDR.",
      "$ref": "Agent.json"
    },
    "externalIdentifier": {
      "description": "Identifier for the resource within SDR but outside of TACO. DRUID or UUID depending on resource type. Constant across resource versions. What clients will use calling TACO. Same as 'identification.identifier'",
      "type": "string"
    },
    "label": {
      "description": "Primary processing label (can be same as title) for a DRO.",
      "type": "string"
    },
    "tacoIdentifier": {
      "description": "Identifier for the resource within TACO. UUID, unique for each new version of a TACO resource.",
      "type": "string"
    },
    "version": {
      "description": "Version for the DRO within SDR.",
      "type": "integer"
    },
    "precedingVersion": {
      "description": "Preceding version for the Object within SDR.",
      "type": "string"
    },
    "followingVersion": {
      "description": "Following version for the Object within SDR.",
      "type": "string"
    },
    "access": {
      "description": "Access Metadata for the DRO.",
      "type": "object",
      "required": ["access", "download"],
      "properties": {
        "access": {
          "description": "Access level for the DRO.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "copyright": {
          "description": "The human readable copyright statement that applies to the DRO.",
          "type": "string"
        },
        "download": {
          "description": "Download level for the DRO metadata.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "embargoReleaseDate": {
          "description": "Date when the DRO is released from an embargo, if an embargo exists.",
          "type": "string",
          "format": "date-time"
        },
        "license": {
          "description": "The license governing reuse of the DRO. Should be an IRI for known licenses (i.e. CC, RightsStatement.org URI, etc.).",
          "type": "string"
        },
        "reuseAndReproductionStatement": {
          "description": "The human readable reuse and reproduction statement that applies to the DRO.",
          "type": "string"
        },
        "termsOfUse": {
          "description": "License or terms of use governing reuse of the DRO. Should be a text statement.",
          "type": "string"
        },
        "visibility": {
          "description": "Percentage of the DRO that is visibility during an embargo period",
          "type": "integer"
        }
      }
    },
    "administrative": {
      "type": "object",
      "description": "Administrative metadata for the SDR resource.",
      "required": ["sdrPreserve"],
      "not": {
        "anyOf": [
          { "required": ["created"] },
          { "required": ["isDescribedBy"] },
          { "required": ["lastUpdated"] }
        ]
      },
      "properties": {
        "created": {
          "description": "When the resource in SDR was created.",
          "type": "string",
          "format": "date-time"
        },
        "deleted": {
          "description": "If the resource has been deleted (but not purged).",
          "type": "boolean"
        },
        "gravestoneMessage": {
          "description": "Message describing why the object was deleted.",
          "type": "string"
        },
        "isDescribedBy": {
          "description": "Pointer to the PURL/XML file that is a traditional representation of the metadata for the DRO.",
          "type": "string"
        },
        "lastUpdated": {
          "description": "When the resource in SDR was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "partOfProject": {
          "description": "Administrative or Internal project this resource is a part of.",
          "type": "string"
        },
        "sdrPreserve": {
          "description": "If this resource should be sent to Preservation.",
          "type": "boolean"
        },
        "remediatedBy": {
          "description": "The Agent (User, Group, Application, Department, other) that remediated a DRO in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "identification": {
      "description": "Identifying information for the DRO.",
      "type": "object",
      "not": {"required": ["identifier"]},
      "properties": {
        "catalogLinks": {
          "description": "Links to catalog records for the resource that the DRO represents in whole or part.",
          "type": "array",
          "items": {
            "type": "object",
            "required": ["catalog", "catalogRecordId"],
            "properties": {
              "catalog": {
                "description": "Catalog that is the source of the linked record.",
                "type": "string"
              },
              "catalogRecordId": {
                "description": "Record identifier that is unique within the context of the linked record's catalog.",
                "type": "string"
              },
              "recordSchema": {
                "description": "Metadata schema of the linked record.",
                "type": "string"
              },
              "deriveMetadata": {
                "description": "If the DRO descriptive metadata should be automatically updated when the linked record changes.",
                "type": "boolean"
              },
              "deliverMetadata": {
                "description": "If the linked record should be automatically updated when the DRO descriptive metadata changes.",
                "type": "boolean"
              },
              "recordScope": {
                "description": "Whether the linked record describes a resource that is broader than, equivalent to, or narrower than the resource the DRO represents.",
                "type": "string",
                "enum": ["broader", "equivalent", "narrower"]
              }
            }
          }
        },
        "doi": {
          "description": "Digital Object Identifier (DOI) for the DRO within this repository.",
          "type": "string"
        },
        "identifier": {
          "description": "Identifier for the Digital Repository Object within the Stanford Digital Repository system",
          "type": "string"
        },
        "sameAs": {
          "description": "Another object, either external or internal to the system (if duplication occurs) that is the same digital resource as this DRO.",
          "type": "string"
        },
        "sourceId": {
          "description": "A source resource or object (perhaps but not necessarily analog or physical) that the DRO is a digital representation of.",
          "type": "string"
        },
        "sdrUUID": {
          "type": "string",
          "description": "UUID previously minted for the resource within SDR2 / Fedora 3."
        }
      }
    },
    "permissions": {
      "description": "Permissions Metadata for the DRO.",
      "type": "object",
      "properties": {
        "approvalRequired": {
          "description": "Indicates if approval is required to deposit or manage the resource in SDR.",
          "type": "boolean"
        },
        "approvers": {
          "description": "Agents who are required to approve deposit or management of this resource in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "structural": {
      "description": "Structural metadata for the DRO.",
      "type": "object",
      "required": ["hasAgreement"],
      "properties": {
        "contains": {
          "description": "Filesets that contain the digital representations (Files) of the DRO.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "hasAgreement": {
          "description": "Agreement that covers the deposit of the DRO into SDR.",
          "type": "string"
        },
        "hasMember": {
          "description": "Component or 'children' digital repository objects that are a part or portion of this 'parent' or aggregate DRO.",
          "type": "array",
          "items": [{
            "type": "string"
          }]
        },
        "isTargetOf": {
          "description": "An Annotation instance that applies to the DRO.",
          "type": ["string", "null"]
        },
        "hasMemberOrders": {
          "description": "Provided sequences or orderings of members of the Object, including some metadata about each sequence (i.e. sequence label, sequence type, if the sequence is primary, etc.).",
          "type": "array",
          "items": [{
            "$ref": "Sequence.json"
          }]
        }
      }
    }
  }
}
`,
    "DepositFile.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "File",
  "description": "Binaries that are the basis of what our domain manages. Binaries here do not include metadata files generated for the domain's own management purposes.",
  "type": "object",
  "required": ["@context", "@type", "label", "administrative", "access", "identification", "structural"],
  "not": {
    "anyOf": [
      { "required": ["tacoIdentifier"] },
      { "required": ["version"] },
      { "required": ["externalIdentifier"] }
    ]
  },
  "properties": {
    "@context": {
      "description": "URI for the JSON-LD context definitions.",
      "type": "string",
      "default": "http://sdr.sul.stanford.edu/contexts/taco-base.jsonld"
    },
    "@type": {
      "description": "The content type of the File.",
      "type": "string",
      "default": "http://sdr.sul.stanford.edu/models/sdr3-file.jsonld",
      "enum": [
        "http://sdr.sul.stanford.edu/models/sdr3-file.jsonld"
      ]
    },
    "depositor": {
      "description": "The Agent (User, Group, Application, Department, other) that deposited the File into SDR.",
      "$ref": "Agent.json"
    },
    "externalIdentifier": {
      "description": "Identifier for the resource within SDR but outside of TACO. UUID. Constant across resource versions. What clients will use calling TACO. Same as 'identification.identifier'",
      "type": "string"
    },
    "filename": {
      "description": "Filename for a file. Can be same as label.",
      "type": "string"
    },
    "format": {
      "description": "Format of the File.",
      "type": "string"
    },
    "hasMessageDigests": {
      "description": "The output of the message digest algorithm.",
      "type": "object"
    },
    "hasMimeType": {
      "description": "MIME Type of the File.",
      "type": "string"
    },
    "label": {
      "description": "Primary processing label (can be same as title) for a File.",
      "type": "string"
    },
    "presentation": {
      "description": "Presentation data for the File.",
      "type": "object"
    },
    "size": {
      "description": "Size of the File (binary) in bytes.",
      "type": "integer"
    },
    "tacoIdentifier": {
      "description": "Identifier for the resource within TACO. UUID, unique for each new version of a TACO resource.",
      "type": "string"
    },
    "use": {
      "description": "Use for the File.",
      "type": "string"
    },
    "version": {
      "description": "Version for the File within SDR.",
      "type": "integer",
      "default": 0
    },
    "precedingVersion": {
      "description": "Preceding version for the File within SDR.",
      "type": "string"
    },
    "followingVersion": {
      "description": "Following version for the File within SDR.",
      "type": "string"
    },
    "access": {
      "description": "Access Metadata for the File.",
      "type": "object",
      "required": ["access", "download"],
      "properties": {
        "access": {
          "description": "Access level for the File.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"],
          "default": "dark"
        },
        "download": {
          "description": "Download level for the File binary.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"],
          "default": "dark"
        }
      }
    },
    "administrative": {
      "type": "object",
      "description": "Administrative metadata for the SDR resource.",
      "required": ["sdrPreserve"],
      "not": {"required": ["created"]},
      "properties": {
        "created": {
          "description": "When the resource in SDR was created.",
          "type": "string",
          "format": "date-time"
        },
        "deleted": {
          "description": "If the resource has been deleted (but not purged).",
          "type": "boolean",
          "default": false
        },
        "gravestoneMessage": {
          "description": "Message describing why the resource was deleted.",
          "type": "string"
        },
        "lastUpdated": {
          "description": "When the resource in SDR was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "partOfProject": {
          "description": "Administrative or Internal project this resource is a part of.",
          "type": "string"
        },
        "sdrPreserve": {
          "description": "If this resource should be sent to Preservation.",
          "type": "boolean",
          "default": false
        },
        "remediatedBy": {
          "description": "The Agent (User, Group, Application, Department, other) that remediated this File in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "identification": {
      "description": "Identifying information for the File.",
      "type": "object",
      "not": {"required": ["identifier"]},
      "properties": {
        "filename": {
          "description": "Filename for the File from originating systems.",
          "type": "string"
        },
        "identifier": {
          "description": "Identifier for the File within the Stanford Digital Repository system",
          "type": "string"
        },
        "sdrUUID": {
          "type": "string",
          "description": "UUID previously minted for the resource within SDR2 / Fedora 3."
        }
      }
    },
    "structural": {
      "description": "Structural metadata for the File.",
      "type": "object",
      "properties": {
        "isContainedBy": {
          "description": "Fileset that contains this File.",
          "type": "string"
        },
        "isTargetOf": {
          "description": "An Annotation instance that applies to this File.",
          "type": ["string", "null"]
        }
      }
    }
  }
}
`,
    "DepositFileset.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Fileset",
  "description": "Relevant groupings of Files. Also called a File Grouping.",
  "type": "object",
  "required": ["@context", "@type", "label", "administrative", "access", "identification", "structural"],
  "not": {
    "anyOf": [
      { "required": ["tacoIdentifier"] },
      { "required": ["version"] },
      { "required": ["externalIdentifier"] }
    ]
  },
  "properties": {
    "@context": {
      "description": "URI for the JSON-LD context definitions.",
      "type": "string"
    },
    "@type": {
      "description": "The content type of the Fileset.",
      "type": "string",
      "enum": [
        "http://sdr.sul.stanford.edu/models/sdr3-fileset.jsonld"
      ]
    },
    "depositor": {
      "description": "The Agent (User, Group, Application, Department, other) that deposited the Fileset into SDR.",
      "$ref": "Agent.json"
    },
    "label": {
      "description": "Primary processing label (can be same as title) for a Fileset.",
      "type": "string"
    },
    "externalIdentifier": {
      "description": "Identifier for the resource within SDR but outside of TACO. UUID. Constant across resource versions. What clients will use calling TACO. Same as 'identification.identifier'",
      "type": "string"
    },
    "tacoIdentifier": {
      "description": "Identifier for the resource within TACO. UUID, unique for each new version of a TACO resource.",
      "type": "string"
    },
    "version": {
      "description": "Version for the Fileset within SDR.",
      "type": "integer"
    },
    "precedingVersion": {
      "description": "Preceding version for the Fileset within SDR.",
      "type": "string"
    },
    "followingVersion": {
      "description": "Following version for the Fileset within SDR.",
      "type": "string"
    },
    "access": {
      "description": "Access Metadata for the Fileset.",
      "type": "object",
      "required": ["access", "download"],
      "properties": {
        "access": {
          "description": "Access level for the Fileset.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "download": {
          "description": "Download level for the Fileset metadata.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        }
      }
    },
    "administrative": {
      "type": "object",
      "description": "Administrative metadata for the SDR resource.",
      "required": ["sdrPreserve"],
      "not": {
        "anyOf": [
          { "required": ["created"] },
          { "required": ["lastUpdated"] }
        ]
      },
      "properties": {
        "created": {
          "description": "When the resource in SDR was created.",
          "type": "string",
          "format": "date-time"
        },
        "deleted": {
          "description": "If the resource has been deleted (but not purged).",
          "type": "boolean"
        },
        "gravestoneMessage": {
          "description": "Message describing why the resource was deleted.",
          "type": "string"
        },
        "lastUpdated": {
          "description": "When the resource in SDR was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "partOfProject": {
          "description": "Administrative or Internal project this resource is a part of.",
          "type": "string"
        },
        "sdrPreserve": {
          "description": "If this resource should be sent to Preservation.",
          "type": "boolean"
        },
        "remediatedBy": {
          "description": "The Agent (User, Group, Application, Department, other) that remediated a Fileset in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "identification": {
      "description": "Identifying information for the Fileset.",
      "type": "object",
      "not": {"required": ["identifier"]},
      "properties": {
        "identifier": {
          "description": "Identifier for the Fileset within the Stanford Digital Repository system",
          "type": "string"
        },
        "sdrUUID": {
          "type": "string",
          "description": "UUID previously minted for the resource within SDR2 / Fedora 3."
        }
      }
    },
    "structural": {
      "description": "Structural metadata for the Fileset.",
      "type": "object",
      "required": ["isContainedBy"],
      "properties": {
        "isContainedBy": {
          "description": "Parent DRO that is represented by the files in this Fileset.",
          "type": "string"
        },
        "isTargetOf": {
          "description": "An Annotation instance that applies to this Fileset.",
          "type": ["string", "null"]
        }
      }
    }
  }
}
`,
    "DepositResource.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Deposit Resource",
  "description": "Deposit Request Domain Resource (Collection, Object, Fileset, or File or any subclass of those) Request Body. For TACO API high-level validation of incoming / outgoing resources.",
  "type": "object",
  "oneOf": [
    {"$ref": "DepositCollection.json"},
    {"$ref": "DepositDRO.json"},
    {"$ref": "DepositFileset.json"}
  ]
}
`,
    "File.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "File",
  "description": "Binaries that are the basis of what our domain manages. Binaries here do not include metadata files generated for the domain's own management purposes.",
  "type": "object",
  "required": ["@context", "@type", "externalIdentifier", "label", "tacoIdentifier", "version", "access", "administrative", "identification", "structural"],
  "properties": {
    "@context": {
      "description": "URI for the JSON-LD context definitions.",
      "type": "string"
    },
    "@type": {
      "description": "The content type of the File.",
      "type": "string",
      "enum": [
        "http://sdr.sul.stanford.edu/models/sdr3-file.jsonld"
      ]
    },
    "depositor": {
      "description": "The Agent (User, Group, Application, Department, other) that deposited the File into SDR.",
      "$ref": "Agent.json"
    },
    "externalIdentifier": {
      "description": "Identifier for the resource within SDR but outside of TACO. UUID. Constant across resource versions. What clients will use calling TACO. Same as 'identification.identifier'",
      "type": "string"
    },
    "filename": {
      "description": "Filename for a file. Can be same as label.",
      "type": "string"
    },
    "followingVersion": {
      "description": "Following version for the File within SDR.",
      "type": "string"
    },
    "format": {
      "description": "Format of the File.",
      "type": "string"
    },
    "hasMessageDigests": {
      "description": "The output of the message digest algorithm.",
      "type": "object"
    },
    "hasMimeType": {
      "description": "MIME Type of the File.",
      "type": "string"
    },
    "label": {
      "description": "Primary processing label (can be same as title) for a File.",
      "type": "string"
    },
    "location": {
      "description": "Location for the binary in the persistence filestore. Should be resolvable.",
      "type": "string",
      "format": "uri"
    },
    "precedingVersion": {
      "description": "Preceding version for the File within SDR.",
      "type": "string"
    },
    "presentation": {
      "description": "Presentation data for the File.",
      "type": "object"
    },
    "size": {
      "description": "Size of the File (binary) in bytes.",
      "type": "integer"
    },
    "tacoIdentifier": {
      "description": "Identifier for the resource within TACO. UUID, unique for each new version of a TACO resource.",
      "type": "string"
    },
    "use": {
      "description": "Use for the File.",
      "type": "string"
    },
    "version": {
      "description": "Version for the File within SDR.",
      "type": "integer"
    },
    "access": {
      "description": "Access Metadata for the File.",
      "type": "object",
      "required": ["access", "download"],
      "properties": {
        "access": {
          "description": "Access level for the File.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "download": {
          "description": "Download level for the File binary.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        }
      }
    },
    "administrative": {
      "type": "object",
      "description": "Administrative metadata for the SDR resource.",
      "required": ["created", "sdrPreserve"],
      "properties": {
        "created": {
          "description": "When the resource in SDR was created.",
          "type": "string",
          "format": "date-time"
        },
        "deleted": {
          "description": "If the resource has been deleted (but not purged).",
          "type": "boolean"
        },
        "gravestoneMessage": {
          "description": "Message describing why the resource was deleted.",
          "type": "string"
        },
        "lastUpdated": {
          "description": "When the resource in SDR was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "partOfProject": {
          "description": "Administrative or Internal project this resource is a part of.",
          "type": "string"
        },
        "sdrPreserve": {
          "description": "If this resource should be sent to Preservation.",
          "type": "boolean"
        },
        "remediatedBy": {
          "description": "The Agent (User, Group, Application, Department, other) that remediated this File in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "identification": {
      "description": "Identifying information for the File.",
      "type": "object",
      "required": ["identifier", "sdrUUID"],
      "properties": {
        "filename": {
          "description": "Filename for the File from originating systems.",
          "type": "string"
        },
        "identifier": {
          "description": "Identifier for the File within the Stanford Digital Repository system",
          "type": "string"
        },
        "sdrUUID": {
          "type": "string",
          "description": "UUID previously minted for the resource within SDR2 / Fedora 3."
        }
      }
    },
    "structural": {
      "description": "Structural metadata for the File.",
      "type": "object",
      "required": ["isContainedBy"],
      "properties": {
        "isContainedBy": {
          "description": "Fileset that contains this File.",
          "type": "string"
        },
        "isTargetOf": {
          "description": "An Annotation instance that applies to this File.",
          "type": ["string", "null"]
        }
      }
    }
  }
}
`,
    "Fileset.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Fileset",
  "description": "Relevant groupings of Files. Also called a File Grouping.",
  "type": "object",
  "required": ["@context", "@type", "externalIdentifier", "tacoIdentifier", "label", "version", "administrative", "access", "identification", "structural"],
  "properties": {
    "@context": {
      "description": "URI for the JSON-LD context definitions.",
      "type": "string"
    },
    "@type": {
      "description": "The content type of the Fileset.",
      "type": "string",
      "enum": [
        "http://sdr.sul.stanford.edu/models/sdr3-fileset.jsonld"
      ]
    },
    "depositor": {
      "description": "The Agent (User, Group, Application, Department, other) that deposited the Fileset into SDR.",
      "$ref": "Agent.json"
    },
    "label": {
      "description": "Primary processing label (can be same as title) for a Fileset.",
      "type": "string"
    },
    "externalIdentifier": {
      "description": "Identifier for the resource within SDR but outside of TACO. UUID. Constant across resource versions. What clients will use calling TACO. Same as 'identification.identifier'",
      "type": "string"
    },
    "tacoIdentifier": {
      "description": "Identifier for the resource within TACO. UUID, unique for each new version of a TACO resource.",
      "type": "string"
    },
    "version": {
      "description": "Version for the Fileset within SDR.",
      "type": "integer"
    },
    "precedingVersion": {
      "description": "Preceding version for the Fileset within SDR.",
      "type": "string"
    },
    "followingVersion": {
      "description": "Following version for the Fileset within SDR.",
      "type": "string"
    },
    "access": {
      "description": "Access Metadata for the Fileset.",
      "type": "object",
      "required": ["access", "download"],
      "properties": {
        "access": {
          "description": "Access level for the Fileset.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        },
        "download": {
          "description": "Download level for the Fileset metadata.",
          "type": "string",
          "enum": ["world", "stanford", "location-based", "citation-only", "dark"]
        }
      }
    },
    "administrative": {
      "type": "object",
      "description": "Administrative metadata for the SDR resource.",
      "required": ["created", "sdrPreserve"],
      "properties": {
        "created": {
          "description": "When the resource in SDR was created.",
          "type": "string",
          "format": "date-time"
        },
        "deleted": {
          "description": "If the resource has been deleted (but not purged).",
          "type": "boolean"
        },
        "gravestoneMessage": {
          "description": "Message describing why the resource was deleted.",
          "type": "string"
        },
        "lastUpdated": {
          "description": "When the resource in SDR was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "partOfProject": {
          "description": "Administrative or Internal project this resource is a part of.",
          "type": "string"
        },
        "sdrPreserve": {
          "description": "If this resource should be sent to Preservation.",
          "type": "boolean"
        },
        "remediatedBy": {
          "description": "The Agent (User, Group, Application, Department, other) that remediated a Fileset in SDR.",
          "type": "array",
          "items": {
            "$ref": "Agent.json"
          }
        }
      }
    },
    "identification": {
      "description": "Identifying information for the Fileset.",
      "type": "object",
      "required": ["identifier"],
      "properties": {
        "identifier": {
          "description": "Identifier for the Fileset within the Stanford Digital Repository system",
          "type": "string"
        },
        "sdrUUID": {
          "type": "string",
          "description": "UUID previously minted for the resource within SDR2 / Fedora 3."
        }
      }
    },
    "structural": {
      "description": "Structural metadata for the Fileset.",
      "type": "object",
      "required": ["isContainedBy"],
      "properties": {
        "isContainedBy": {
          "description": "Parent DRO that is represented by the files in this Fileset.",
          "type": "string"
        },
        "isTargetOf": {
          "description": "An Annotation instance that applies to this Fileset.",
          "type": ["string", "null"]
        }
      }
    }
  }
}
`,
    "Resource.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Resource",
  "description": "Update / Retrieve Request Domain Resource (Collection, Object, Fileset, or File or any subclass of those) Request Body. For TACO API high-level validation of incoming / outgoing resources.",
  "type": "object",
  "oneOf": [
    {"$ref": "Collection.json"},
    {"$ref": "DRO.json"},
    {"$ref": "Fileset.json"},
    {"$ref": "File.json"}
  ]
}
`,
    "Sequence.json": `{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Resource Sequence",
  "description": "A sequence or ordering of resources within a Collection or Object.",
  "type": "object",
  "required": ["@type", "label", "startMember", "members"],
  "properties": {
    "@context": {
      "description": "URI for the JSON-LD context definitions.",
      "type": "string"
    },
    "@type": {
      "description": "The type of Sequence.",
      "type": "string",
      "enum": ["http://sdr.sul.stanford.edu/models/sdr3-sequence.jsonld",
        "http://sdr.sul.stanford.edu/models/sdr3-primary-sequence.jsonld"
      ]
    },
    "label": {
      "description": "Label for the sequence or ordering.",
      "type": "string"
    },
    "startMember": {
      "description": "Identifier for the first member of the sequence.",
      "type": "string"
    },
    "members": {
      "description": "Identifiers for Members in their stated Order for the Sequence.",
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  }
}
`,
  }
)
