// Code generated by go-swagger; DO NOT EDIT.

package work

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddWorkMethodNotAllowedCode is the HTTP code returned for type AddWorkMethodNotAllowed
const AddWorkMethodNotAllowedCode int = 405

/*AddWorkMethodNotAllowed Invalid input

swagger:response addWorkMethodNotAllowed
*/
type AddWorkMethodNotAllowed struct {
}

// NewAddWorkMethodNotAllowed creates AddWorkMethodNotAllowed with default headers values
func NewAddWorkMethodNotAllowed() *AddWorkMethodNotAllowed {
	return &AddWorkMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddWorkMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
