// Code generated by go-swagger; DO NOT EDIT.

package work

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddWorkHandlerFunc turns a function with the right signature into a add work handler
type AddWorkHandlerFunc func(AddWorkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddWorkHandlerFunc) Handle(params AddWorkParams) middleware.Responder {
	return fn(params)
}

// AddWorkHandler interface for that can handle valid add work params
type AddWorkHandler interface {
	Handle(AddWorkParams) middleware.Responder
}

// NewAddWork creates a new http.Handler for the add work operation
func NewAddWork(ctx *middleware.Context, handler AddWorkHandler) *AddWork {
	return &AddWork{Context: ctx, Handler: handler}
}

/*AddWork swagger:route POST /resource work addWork

Add a new work

*/
type AddWork struct {
	Context *middleware.Context
	Handler AddWorkHandler
}

func (o *AddWork) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddWorkParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
