// Code generated by go-swagger; DO NOT EDIT.

package work

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindWorkByIDHandlerFunc turns a function with the right signature into a find work by Id handler
type FindWorkByIDHandlerFunc func(FindWorkByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindWorkByIDHandlerFunc) Handle(params FindWorkByIDParams) middleware.Responder {
	return fn(params)
}

// FindWorkByIDHandler interface for that can handle valid find work by Id params
type FindWorkByIDHandler interface {
	Handle(FindWorkByIDParams) middleware.Responder
}

// NewFindWorkByID creates a new http.Handler for the find work by Id operation
func NewFindWorkByID(ctx *middleware.Context, handler FindWorkByIDHandler) *FindWorkByID {
	return &FindWorkByID{Context: ctx, Handler: handler}
}

/*FindWorkByID swagger:route GET /resource/{id} work findWorkById

Find work by ID

Returns a single work

*/
type FindWorkByID struct {
	Context *middleware.Context
	Handler FindWorkByIDHandler
}

func (o *FindWorkByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindWorkByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
