// Code generated by go-swagger; DO NOT EDIT.

package work

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sul-dlss-labs/taco/models"
)

// FindWorkByIDOKCode is the HTTP code returned for type FindWorkByIDOK
const FindWorkByIDOKCode int = 200

/*FindWorkByIDOK successful operation

swagger:response findWorkByIdOK
*/
type FindWorkByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Work `json:"body,omitempty"`
}

// NewFindWorkByIDOK creates FindWorkByIDOK with default headers values
func NewFindWorkByIDOK() *FindWorkByIDOK {
	return &FindWorkByIDOK{}
}

// WithPayload adds the payload to the find work by Id o k response
func (o *FindWorkByIDOK) WithPayload(payload *models.Work) *FindWorkByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find work by Id o k response
func (o *FindWorkByIDOK) SetPayload(payload *models.Work) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindWorkByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindWorkByIDBadRequestCode is the HTTP code returned for type FindWorkByIDBadRequest
const FindWorkByIDBadRequestCode int = 400

/*FindWorkByIDBadRequest Invalid ID supplied

swagger:response findWorkByIdBadRequest
*/
type FindWorkByIDBadRequest struct {
}

// NewFindWorkByIDBadRequest creates FindWorkByIDBadRequest with default headers values
func NewFindWorkByIDBadRequest() *FindWorkByIDBadRequest {
	return &FindWorkByIDBadRequest{}
}

// WriteResponse to the client
func (o *FindWorkByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// FindWorkByIDNotFoundCode is the HTTP code returned for type FindWorkByIDNotFound
const FindWorkByIDNotFoundCode int = 404

/*FindWorkByIDNotFound Pet not found

swagger:response findWorkByIdNotFound
*/
type FindWorkByIDNotFound struct {
}

// NewFindWorkByIDNotFound creates FindWorkByIDNotFound with default headers values
func NewFindWorkByIDNotFound() *FindWorkByIDNotFound {
	return &FindWorkByIDNotFound{}
}

// WriteResponse to the client
func (o *FindWorkByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
