// Code generated by go-swagger; DO NOT EDIT.

package work

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateWorkHandlerFunc turns a function with the right signature into a update work handler
type UpdateWorkHandlerFunc func(UpdateWorkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateWorkHandlerFunc) Handle(params UpdateWorkParams) middleware.Responder {
	return fn(params)
}

// UpdateWorkHandler interface for that can handle valid update work params
type UpdateWorkHandler interface {
	Handle(UpdateWorkParams) middleware.Responder
}

// NewUpdateWork creates a new http.Handler for the update work operation
func NewUpdateWork(ctx *middleware.Context, handler UpdateWorkHandler) *UpdateWork {
	return &UpdateWork{Context: ctx, Handler: handler}
}

/*UpdateWork swagger:route PUT /resource work updateWork

Update an existing work

*/
type UpdateWork struct {
	Context *middleware.Context
	Handler UpdateWorkHandler
}

func (o *UpdateWork) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateWorkParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
