// Code generated by go-swagger; DO NOT EDIT.

package work

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateWorkBadRequestCode is the HTTP code returned for type UpdateWorkBadRequest
const UpdateWorkBadRequestCode int = 400

/*UpdateWorkBadRequest Invalid ID supplied

swagger:response updateWorkBadRequest
*/
type UpdateWorkBadRequest struct {
}

// NewUpdateWorkBadRequest creates UpdateWorkBadRequest with default headers values
func NewUpdateWorkBadRequest() *UpdateWorkBadRequest {
	return &UpdateWorkBadRequest{}
}

// WriteResponse to the client
func (o *UpdateWorkBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateWorkNotFoundCode is the HTTP code returned for type UpdateWorkNotFound
const UpdateWorkNotFoundCode int = 404

/*UpdateWorkNotFound Work not found

swagger:response updateWorkNotFound
*/
type UpdateWorkNotFound struct {
}

// NewUpdateWorkNotFound creates UpdateWorkNotFound with default headers values
func NewUpdateWorkNotFound() *UpdateWorkNotFound {
	return &UpdateWorkNotFound{}
}

// WriteResponse to the client
func (o *UpdateWorkNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateWorkMethodNotAllowedCode is the HTTP code returned for type UpdateWorkMethodNotAllowed
const UpdateWorkMethodNotAllowedCode int = 405

/*UpdateWorkMethodNotAllowed Validation exception

swagger:response updateWorkMethodNotAllowed
*/
type UpdateWorkMethodNotAllowed struct {
}

// NewUpdateWorkMethodNotAllowed creates UpdateWorkMethodNotAllowed with default headers values
func NewUpdateWorkMethodNotAllowed() *UpdateWorkMethodNotAllowed {
	return &UpdateWorkMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateWorkMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
